- name: Perform some tasks
  hosts: webservers
  vars_files: new_vault.yml
  remote_user: ec2-user

  tasks:
  - name: Install git and python3
    yum:
      name: 
        - git
        - python3
      state: present
    become: yes
  - name: Install poetry
    shell: 
      cmd: 'curl -sSL https://install.python-poetry.org |  python3 -'
      creates: /home/ec2-user/.local/bin/poetry
  - name: Set up directory
    file:
      path: /opt/todoapp
      state: directory
      owner: ec2-user
      mode: u=rwx,g=r,o=r
    become: yes
  - name: Git checkout
    git:
      repo: https://github.com/aliwen-soft/DevOps-Course-Starter
      dest: /opt/todoapp
      version: Module-Four-New
    become: yes
  - name: make env template
    ansible.builtin.template:
      src: .env.j2
      dest: /opt/todoapp/.env
      mode: u=xrw
  - name: perform poetry install
    command: /home/ec2-user/.local/bin/poetry install
    args:
      chdir: /opt/todoapp/
  - name: Copy over service file
    copy:
      src: todoapp.service
      dest: /etc/systemd/system/todoapp.service
    become: yes
  - name: start service
    ansible.builtin.systemd:
      state: started
      name: todoapp
    become: yes
