name: Continuous Integration
on: 
  pull_request:
    branches:
      -main
    paths-ignore:
      - 'documentation/**'
      - 'README.md'
  push:
    paths-ignore:
      - 'documentation/**'
      - 'README.md'

env:
  TF_VAR_prefix: 'aliwen-gh-b'
  TF_VAR_todo_secret: ${{ secrets.TF_VAR_TODO_SECRET }}
  TF_VAR_github_id: ${{ secrets.TF_VAR_GITHUB_ID }}
  TF_VAR_github_secret: ${{ secrets.TF_VAR_GITHUB_SECRET }}
  TF_VAR_loggly_secret: ${{ secrets.LOGGLY_TOKEN }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}



jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run:  docker build --target test --tag todo_app:test .
    - run:  docker run --env-file=.env.test todo_app:test
  deploy:
    name: Deploy main branch
    needs: build
    runs-on: ubuntu-latest
    if: (github.event_name == 'push')
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: 'aliwen'
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - run: docker build --target production --tag aliwen/todo_app:latest .
    - run: docker push aliwen/todo_app:latest
    - run: terraform init
    - run: terraform apply -auto-approve
    - run: curl -dH -X POST "$(terraform output -raw webhook_url)" --fail
  publish:
    runs-on: ubuntu-latest
    needs: deploy
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main')
    steps:
      - uses: actions/checkout@v2
      - uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          heroku_api_key: ${{secrets.HEROKU_TOKEN}}
          heroku_app_name: "todo-app-aliwen" 
          email: "alice.wenban@softwire.com"
          docker_options: "--target production"

  